### Which brand and model sell more in Norway between 2007-2017

In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("norway_new_car_sales_by_model.csv", encoding="latin-1")

In [4]:
data

      Year  Month         Make              Model  Quantity   Pct
0     2007      1  Volkswagen   Volkswagen Passat      1267  10.0
1     2007      1      Toyota         Toyota Rav4       819   6.5
2     2007      1      Toyota      Toyota Avensis       787   6.2
3     2007      1  Volkswagen     Volkswagen Golf       720   5.7
4     2007      1      Toyota      Toyota Corolla       691   5.4
...    ...    ...          ...                ...       ...   ...
2689  2017      1     Peugeot        Peugeot 3008       216   1.7
2690  2017      1         Kia            Kia Niro       214   1.6
2691  2017      1       Skoda        Skoda Superb       205   1.6
2692  2017      1         BMW         BMW 2-serie       202   1.5
2693  2017      1       Volvo           Volvo V90       202   1.5

[2694 rows x 6 columns]

In [7]:
data.info() # I need to check do we have empty data or no.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2694 entries, 0 to 2693
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Year      2694 non-null   int64
 1   Month     2694 non-null   int64
 2   Make      2694 non-null   object
 3   Model     2694 non-null   object
 4   Quantity  2694 non-null   int64
 5   Pct       2694 non-null   float64
dtypes: float64(1), int64(3), object(2)
memory usage: 126.4+ KB

In [10]:
data.isnull().sum()

Year        0
Month       0
Make        0
Model       0
Quantity    0
Pct         0
dtype: int64

In [13]:
data.Make.unique()

array(['Volkswagen ', 'Toyota ', 'Peugeot ', 'Skoda ', 'Ford ', 'Volvo ',
       'Audi ', 'Opel ', 'BMW ', 'Honda ', 'Saab ', 'Mitsubishi ',
       'Nissan ', 'Mazda ', 'Subaru ', 'Hyundai ', 'Suzuki ', 'Kia ',
       'Mercedes-Benz ', 'Citroen ', '\xa0Mercedes-Benz ', 'Tesla ',
       'Renault '], dtype=object)

In [15]:
# As you see, we have different Mercedes Benz as a  '\xa0Mercedes-Benz '. Also there is one space end of the all Make column
data.Make = data.Make.str.strip()

In [20]:
data.Make

0       Volkswagen
1           Toyota
2           Toyota
3       Volkswagen
4           Toyota
           ...
2689       Peugeot
2690           Kia
2691         Skoda
2692           BMW
2693         Volvo
Name: Make, Length: 2694, dtype: object

In [39]:
len(data.Make.unique())  #after all that, it will be all unique.

22

In [31]:
# We need to check the types of words. Maybe there is different types of toyota. (Like "toyota" or "TOYOTA")
# We can define a function for it. Because we can use it for all column
def f(x):
    if type(x) == str:
        return x.strip().lower().title()
    else:
        return x

In [32]:
data.map(f)

      Year  Month        Make              Model  Quantity   Pct
0     2007      1  Volkswagen  Volkswagen Passat      1267  10.0
1     2007      1      Toyota        Toyota Rav4       819   6.5
2     2007      1      Toyota     Toyota Avensis       787   6.2
3     2007      1  Volkswagen    Volkswagen Golf       720   5.7
4     2007      1      Toyota     Toyota Corolla       691   5.4
...    ...    ...         ...                ...       ...   ...
2689  2017      1     Peugeot       Peugeot 3008       216   1.7
2690  2017      1         Kia           Kia Niro       214   1.6
2691  2017      1       Skoda       Skoda Superb       205   1.6
2692  2017      1         Bmw        Bmw 2-Serie       202   1.5
2693  2017      1       Volvo          Volvo V90       202   1.5

[2694 rows x 6 columns]

In [38]:
len(data.Make.unique())

22

In [40]:
data

      Year  Month        Make              Model  Quantity   Pct
0     2007      1  Volkswagen  Volkswagen Passat      1267  10.0
1     2007      1      Toyota        Toyota Rav4       819   6.5
2     2007      1      Toyota     Toyota Avensis       787   6.2
3     2007      1  Volkswagen    Volkswagen Golf       720   5.7
4     2007      1      Toyota     Toyota Corolla       691   5.4
...    ...    ...         ...                ...       ...   ...
2689  2017      1     Peugeot       Peugeot 3008       216   1.7
2690  2017      1         Kia           Kia Niro       214   1.6
2691  2017      1       Skoda       Skoda Superb       205   1.6
2692  2017      1         BMW        BMW 2-serie       202   1.5
2693  2017      1       Volvo          Volvo V90       202   1.5

[2694 rows x 6 columns]

In [45]:
len(data[(data.Make == "Toyota") & (data.Quantity > 500)])

23

In [48]:
data[(data.Model == "Toyota Rav4") & (data.Quantity > 500)]

      Year  Month    Make        Model  Quantity  Pct
1     2007      1  Toyota  Toyota Rav4       819  6.5
2020  2015      1  Toyota  Toyota Rav4       535  5.1
2574  2016      8  Toyota  Toyota Rav4       735  5.6
2594  2016      9  Toyota  Toyota Rav4       581  4.2
2635  2016     11  Toyota  Toyota Rav4       513  3.9

In [49]:
data.query("Quantity > 500 and Model == 'Toyota Rav4'")

      Year  Month    Make        Model  Quantity  Pct
1     2007      1  Toyota  Toyota Rav4       819  6.5
2020  2015      1  Toyota  Toyota Rav4       535  5.1
2574  2016      8  Toyota  Toyota Rav4       735  5.6
2594  2016      9  Toyota  Toyota Rav4       581  4.2
2635  2016     11  Toyota  Toyota Rav4       513  3.9

In [57]:
data.query("2010 < Year < 2015 & Make == 'Toyota'").Quantity.sum()

np.int64(49826)

In [60]:
data_toyota = data[(data.Make=="Toyota")]
data_toyota

      Year  Month    Make           Model  Quantity  Pct
1     2007      1  Toyota     Toyota Rav4       819  6.5
2     2007      1  Toyota  Toyota Avensis       787  6.2
4     2007      1  Toyota  Toyota Corolla       691  5.4
7     2007      1  Toyota    Toyota Yaris       402  3.2
21    2007      2  Toyota  Toyota Avensis       540  5.5
...    ...    ...     ...             ...       ...  ...
2671  2016     12  Toyota    Toyota Prius       104  0.8
2676  2017      1  Toyota     Toyota Rav4       473  3.6
2680  2017      1  Toyota    Toyota Yaris       343  2.6
2682  2017      1  Toyota    Toyota Auris       280  2.1
2684  2017      1  Toyota     Toyota C-HR       246  1.9

[492 rows x 6 columns]

In [63]:
data_toyota.sort_values(by = ["Year","Quantity"], ascending = [True,False])

      Year  Month    Make           Model  Quantity       Pct
1     2007      1  Toyota     Toyota Rav4       819  6.500000
2     2007      1  Toyota  Toyota Avensis       787  6.200000
4     2007      1  Toyota  Toyota Corolla       691  5.400000
121   2007      7  Toyota  Toyota Avensis       587  4.900000
21    2007      2  Toyota  Toyota Avensis       540  5.500000
...    ...    ...     ...             ...       ...       ...
2343  2016      1  Toyota    Toyota Prius        55  0.500409
2676  2017      1  Toyota     Toyota Rav4       473  3.600000
2680  2017      1  Toyota    Toyota Yaris       343  2.600000
2682  2017      1  Toyota    Toyota Auris       280  2.100000
2684  2017      1  Toyota     Toyota C-HR       246  1.900000

[492 rows x 6 columns]

In [68]:
data.set_index(["Year","Month","Make"])

                                   Model  Quantity   Pct
Year Month Make
2007 1     Volkswagen  Volkswagen Passat      1267  10.0
           Toyota            Toyota Rav4       819   6.5
           Toyota         Toyota Avensis       787   6.2
           Volkswagen    Volkswagen Golf       720   5.7
           Toyota         Toyota Corolla       691   5.4
...                                  ...       ...   ...
2017 1     Peugeot          Peugeot 3008       216   1.7
           Kia                  Kia Niro       214   1.6
           Skoda            Skoda Superb       205   1.6
           BMW               BMW 2-serie       202   1.5
           Volvo               Volvo V90       202   1.5

[2694 rows x 3 columns]

In [69]:
data = pd.read_csv("norway_new_car_sales_by_model.csv",encoding = "latin-1")

In [70]:
data

      Year  Month         Make              Model  Quantity   Pct
0     2007      1  Volkswagen   Volkswagen Passat      1267  10.0
1     2007      1      Toyota         Toyota Rav4       819   6.5
2     2007      1      Toyota      Toyota Avensis       787   6.2
3     2007      1  Volkswagen     Volkswagen Golf       720   5.7
4     2007      1      Toyota      Toyota Corolla       691   5.4
...    ...    ...          ...                ...       ...   ...
2689  2017      1     Peugeot        Peugeot 3008       216   1.7
2690  2017      1         Kia            Kia Niro       214   1.6
2691  2017      1       Skoda        Skoda Superb       205   1.6
2692  2017      1         BMW         BMW 2-serie       202   1.5
2693  2017      1       Volvo           Volvo V90       202   1.5

[2694 rows x 6 columns]

In [77]:
maketotal=data.pivot_table(values="Quantity",index=["Make","Model"],aggfunc= "sum");maketotal

                                         Quantity
Make            Model
Audi            Audi A3                     12889
                Audi A4                     15453
                Audi A6                       131
                Audi Q3                       218
BMW             BMW 1-serie                   608
...                                           ...
Volvo           Volvo V70                   32790
                Volvo V90                     202
                Volvo XC60                  11279
                Volvo XC90                   1477
 Mercedes-Benz   Mercedes-Benz A-klasse       184

[90 rows x 1 columns]

In [88]:
maketotal.sort_index(axis = 1,ascending = False)

                                         Quantity
Make            Model
Audi            Audi A3                     12889
                Audi A4                     15453
                Audi A6                       131
                Audi Q3                       218
BMW             BMW 1-serie                   608
...                                           ...
Volvo           Volvo V70                   32790
                Volvo V90                     202
                Volvo XC60                  11279
                Volvo XC90                   1477
 Mercedes-Benz   Mercedes-Benz A-klasse       184

[90 rows x 1 columns]

In [89]:
data

      Year  Month         Make              Model  Quantity   Pct
0     2007      1  Volkswagen   Volkswagen Passat      1267  10.0
1     2007      1      Toyota         Toyota Rav4       819   6.5
2     2007      1      Toyota      Toyota Avensis       787   6.2
3     2007      1  Volkswagen     Volkswagen Golf       720   5.7
4     2007      1      Toyota      Toyota Corolla       691   5.4
...    ...    ...          ...                ...       ...   ...
2689  2017      1     Peugeot        Peugeot 3008       216   1.7
2690  2017      1         Kia            Kia Niro       214   1.6
2691  2017      1       Skoda        Skoda Superb       205   1.6
2692  2017      1         BMW         BMW 2-serie       202   1.5
2693  2017      1       Volvo           Volvo V90       202   1.5

[2694 rows x 6 columns]

In [91]:
data.loc[50:60]

    Year  Month         Make              Model  Quantity  Pct
50  2007      3        Audi             Audi A4       239  2.1
51  2007      3       Volvo           Volvo V70       236  2.1
52  2007      3     Peugeot         Peugeot 207       229  2.0
53  2007      3        Ford          Ford S-Max       219  1.9
54  2007      3        Saab            Saab 9-3       214  1.9
55  2007      3        Opel          Opel Astra       211  1.9
56  2007      3       Volvo           Volvo V50       197  1.7
57  2007      3  Volkswagen     Volkswagen Polo       197  1.7
58  2007      3  Volkswagen   Volkswagen Touran       194  1.7
59  2007      3        Audi             Audi A3       184  1.6
60  2007      4  Volkswagen   Volkswagen Passat       375  4.2

In [92]:
data.sort_values(by = "Make")

,Year,Month,Make,Model,Quantity,Pct
1569,2013,5,Audi,Audi A3,211,1.756577
774,2010,3,Audi,Audi A4,207,1.800000
342,2008,6,Audi,Audi A4,331,3.400000
1534,2013,3,Audi,Audi A4,139,1.300000
609,2009,7,Audi,Audi A4,246,2.600000
...,...,...,...,...,...,...
2317,2016,1,Volvo,Volvo V60,159,1.446638
1210,2012,1,Volvo,Volvo V60,225,2.100000
1226,2012,2,Volvo,Volvo V70,270,2.500000
2693,2017,1,Volvo,Volvo V90,202,1.500000
1574,2013,5,Mercedes-Benz,Mercedes-Benz A-klasse,184,1.531802

In [95]:
data_audi= data[data.Make == "Audi "]

In [103]:
data_audi.sort_values(by = ["Year","Quantity"],ascending = [True,False])

      Year  Month   Make    Model  Quantity       Pct
11    2007      1  Audi   Audi A4       269  2.100000
131   2007      7  Audi   Audi A4       247  2.000000
50    2007      3  Audi   Audi A4       239  2.100000
149   2007      8  Audi   Audi A4       223  2.100000
95    2007      5  Audi   Audi A4       221  1.800000
...    ...    ...    ...      ...       ...       ...
2555  2016      7  Audi   Audi A4       157  1.422101
2324  2016      1  Audi   Audi A4       128  1.164589
2385  2016      2  Audi   Audi A4       102  0.834561
2338  2016      1  Audi   Audi A6        66  0.600491
2393  2016      2  Audi   Audi A6        65  0.531828

[146 rows x 6 columns]

In [109]:
data_audi["Model"].str.strip()

11      Audi A4
16      Audi A3
32      Audi A4
36      Audi A3
50      Audi A4
         ...
2587    Audi A3
2608    Audi A3
2625    Audi A3
2642    Audi A3
2657    Audi A3
Name: Model, Length: 146, dtype: object

In [111]:
data_audi["Model"].unique()

array(['Audi A4', 'Audi A3', 'Audi Q3', 'Audi A6'], dtype=object)

In [112]:
total = data_audi.pivot_table(values="Quantity",index=["Make","Model"],aggfunc="sum")

In [113]:
total

               Quantity
Make  Model
Audi  Audi A3     12889
      Audi A4     15453
      Audi A6       131
      Audi Q3       218

In [117]:
total.sort_values(by = "Quantity",)

               Quantity
Make  Model
Audi  Audi A6       131
      Audi Q3       218
      Audi A3     12889
      Audi A4     15453